package com.brasil.transparente.processor.util.constants.estados;

import lombok.Getter;

@Getter
public final class AMConstants {

    public static final String UNIVERSIDADE_DO_ESTADO_DO_AMAZONAS = "UNIVERSIDADE DO ESTADO DO AMAZONAS";
    public static final String DEPARTAMENTO_ESTADUAL_DE_TRANSITO = "DEPARTAMENTO ESTADUAL DE TRANSITO";
    public static final String FUNDO_ESTADUAL_DE_SAUDE = "FUNDO ESTADUAL DE SAUDE";
    public static final String CENTRO_DE_EDUCACAO_TECNOLOGICA_DO_AMAZONAS = "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS";
    public static final String FUNDACAO_DE_VIGILANCIA_EM_SAUDE_DO_ESTADO_DO_AMAZONAS_DRA_ROSEMARY_COSTA_PINTO = "FUNDACAO DE VIGILANCIA EM SAUDE DO ESTADO DO AMAZONAS DRA. ROSEMARY COSTA PINTO";
    public static final String FUNDACAO_HOSPITAL_ADRIANO_JORGE = "FUNDACAO HOSPITAL ADRIANO JORGE";
    public static final String FUNDACAO_CENTRO_DE_CONTROLE_DE_ONCOLOGIA_DO_ESTADO_DO_AMAZONAS = "FUNDACAO CENTRO CONTROLE ONCOLOGIA DO EST AMAZONAS";
    public static final String AGENCIA_DE_DESENVOLVIMENTO_SUSTENTAVEL_DO_AMAZONAS = "AGÊNCIA DE DESENVOLVIMENTO SUSTENTÁVEL DO AMAZONAS";
    public static final String FUNDACAO_HOSPITALAR_DE_HEMATOLOGIA_E_HEMOTERAPIA_DO_AMAZONAS = "FUNDAÇÃO HOSPITALAR HEMATOL E HEMOTER DO AMAZONAS";
    public static final String FUNDO_ESTADUAL_DE_ASSISTENCIA_SOCIAL = "FUNDO ESTADUAL DE ASSISTENCIA SOCIAL";
    public static final String EMPRESA_ESTADUAL_DE_TURISMO = "EMPRESA ESTADUAL DE TURISMO";
    public static final String FUNDACAO_DE_AMPARO_A_PESQUISA_DO_ESTADO_DO_AMAZONAS = "FUNDACAO DE AMPARO À PESQUISA DO EST DO AMAZONAS";
    public static final String INSTITUTO_DE_DESENVOLVIMENTO_AGROPECUARIO_E_FLORESTAL_SUSTENTAVEL_DO_ESTADO_DO_AMAZONAS = "INSTITUTO DE DESENVOLVIMENTO AGROPECUÁRIO E FLORESTAL SUSTENTÁVEL DO ESTADO DO AMAZONAS";
    public static final String FUNDO_ESTADUAL_DE_HABITACAO = "FUNDO ESTADUAL DE HABITAÇÃO";
    public static final String FUNDACAO_DE_MEDICINA_TROPICAL_DOUTOR_HEITOR_VIEIRA_DOURADO = "FUNDACAO DE MEDICINA TROPICAL DOUTOR HEITOR VIEIRA DOURADO";
    public static final String SUPERINTENDENCIA_ESTADUAL_DE_HABITACAO = "SUPERINTENDENCIA ESTADUAL DE HABITAÇÃO";
    public static final String FUNDO_ESTADUAL_DE_SEGURANCA_PUBLICA_DO_ESTADO_DO_AMAZONAS = "FUNDO ESTADUAL DE SEGURANÇA PÚBLICA DO ESTADO DO AMAZONAS";
    public static final String INSTITUTO_DE_PROTECAO_AMBIENTAL_DO_AMAZONAS = "INSTITUTO DE PROTEÇÃO AMBIENTAL  DO AMAZONAS";
    public static final String AGENCIA_DE_DEFESA_AGROPECUARIA_E_FLORESTAL_DO_ESTADO_DO_AMAZONAS = "AGÊNCIA DE DEFESA AGROPECUÁRIA E FLORESTAL DO ESTADO DO AMAZONAS";
    public static final String COMPANHIA_DE_SANEAMENTO_DO_AMAZONAS_SA = "COMPANHIA DE SANEAMENTO DO AMAZONAS S/A";
    public static final String FUNDO_ESTADUAL_DE_PROTECAO_E_DEFESA_CIVIL = "FUNDO ESTADUAL DE PROTEÇÃO E DEFESA CIVIL";
    public static final String FUNDO_ESTADUAL_DE_CULTURA = "FUNDO ESTADUAL DE CULTURA";
    public static final String FUNDACAO_HOSPITALAR_DE_DERMATOLOGIA_TROPICAL_E_VENEREOLOGIA_ALFREDO_DA_MATTA = "FUNDACAO HOSPITALAR DE DERMATOLOGIA TROPICAL E VENEREOLOGIA ALFREDO MATTA";
    public static final String AGENCIA_REGULADORA_DE_SERVICOS_PUBLICOS_DELEGADOS_E_CONTRATADOS_DO_ESTADO_DO_AMA = "AGÊNCIA REGULADORA DE SERVIÇOS PÚBLICOS DELEGADOS E CONTRATADOS DO ESTADO DO AMAZONAS";
    public static final String FUNDACAO_TELEVISAO_E_RADIO_CULTURA_DO_AMAZONAS = "FUNDACAO TELEVISAO E RADIO CULTURA DO AMAZONAS";
    public static final String FUNDO_PENITENCIARIO_DO_ESTADO_DO_AMAZONAS = "FUNDO PENITENCIÁRIO DO ESTADO DO AMAZONAS";
    public static final String FUNDO_PARA_FINANCIAMENTO_DA_MODERNIZACAO_FAZENDARIA_DO_ESTADO_DO_AMAZONAS = "FUNDO PARA FINANCIAMENTO DA MODERNIZAÇÃO FAZENDÁRI";
    public static final String IMPRENSA_OFICIAL_DO_ESTADO_DO_AMAZONAS = "IMPRENSA OFICIAL DO ESTADO DO AMAZONAS";
    public static final String JUNTA_COMERCIAL_DO_ESTADO = "JUNTA COMERCIAL DO ESTADO DO AMAZONAS";
    public static final String SECRETARIA_EXECUTIVA_ERRADICACAO_POBREZA = "SECRETARIA EXECUTIVA DO FUNDO DE PROMOÇÃO SOCIAL E ERRADICAÇÃO DA POBREZA";
    public static final String FUNDO_ESTADUAL_DA_CRIANCA_E_DO_ADOLESCENTE = "FUNDO ESTADUAL DA CRIANCA E DO ADOLESCENTE";
    public static final String FUNDACAO_ESTADUAL_DO_INDIO = "FUNDACAO ESTADUAL DO ÍNDIO";
    public static final String SUPERINTENDENCIA_NAVEGACAO_PORTOS_HIDROVIAS = "SUPERINTENDÊNCIA ESTADUAL DE NAVEGAÇÃO, PORTOS E H";
    public static final String FUNDO_ESPECIAL_DO_CORPO_DE_BOMBEIROS_MILITAR_DO_ESTADO_DO_AMAZONAS = "FUNDO ESPECIAL DO CORPO DE BOMBEIROS MILITAR DO ESTADO DO AMAZONAS";
    public static final String INSTITUTO_DE_PESOS_E_MEDIDAS = "INSTITUTO DE PESOS E MEDIDAS DO ESTADO DO AMAZONAS";
    public static final String FUNDO_ESPECIAL_DA_DEFENSORIA_PUBLICA_DO_ESTADO_DO_AMAZONAS = "FUNDO ESPECIAL DA DEFENSORIA PÚBLICA DO ESTADO  AM";
    public static final String FUNDO_ESTADUAL_DE_REGULARIZACAO_FUNDIARIA = "FUNDO ESTADUAL DE REGULARIZAÇÃO FUNDIÁRIA";
    public static final String FUNDO_ESTADUAL_DE_DEFESA_DO_CONSUMIDOR = "FUNDO ESTADUAL DE DEFESA DO CONSUMIDOR";
    public static final String FUNDACAO_HOSPITAL_DO_CORACAO_FRANCISCA_MENDES = "FUNDACAO HOSPITAL DO CORAÇÃO FRANCISCA MENDES";
    public static final String FUNDO_ESPECIAL_DA_PROCURADORIA_GERAL_DO_ESTADO = "FUNDO ESPECIAL DA PROCURADORIA GERAL DO ESTADO";
    public static final String FUNDO_ESTADUAL_DO_MEIO_AMBIENTE = "FUNDO ESTADUAL DO MEIO AMBIENTE";
    public static final String FUNDO_DE_RESERVA_PARA_AS_ACOES_DE_INTELIGENCIA = "FUNDO DE RESERVA PARA AS AÇÕES DE INTELIGÊNCIA";
    public static final String PROCURADORIA_GERAL_JUSTICA = "PROCURADORIA GERAL DE JUSTICA";
    public static final String MINISTERIO_PUBLICO = "Ministério Público";
    public static final String DEFENSORIA_PUBLICA_DO_ESTADO_DO_AMAZONAS = "DEFENSORIA PÚBLICA DO ESTADO DO AMAZONAS";
    public static final String SECRETARIA_DE_ESTADO_DA_ASSISTENCIA_SOCIAL = "SECRETARIA DE ESTADO DA ASSISTÊNCIA SOCIAL";
    public static final String SECRETARIA_DE_ESTADO_DA_FAZENDA = "SECRETARIA DE ESTADO DA FAZENDA";
    public static final String SECRETARIA_DE_ESTADO_DAS_CIDADES_E_TERRITORIOS = "SECRETARIA DE ESTADO DAS CIDADES E TERRITÓRIOS";
    public static final String SECRETARIA_DE_ESTADO_DE_ADMINISTRACAO_E_GESTAO = "SECRETARIA DE EST DE ADMINISTRAÇÃO E GESTÃO";
    public static final String SECRETARIA_DE_ESTADO_DE_ADMINISTRACAO_PENITENCIARIA = "SECRETARIA DE ESTADO DE ADMINISTRAÇÃO PENITENCIÁRIA";
    public static final String SECRETARIA_DE_ESTADO_DE_CULTURA_E_ECONOMIA_CRIATIVA = "SECRETARIA DE ESTADO DE CULTURA E ECONOMIA CRIATIVA";
    public static final String SECRETARIA_DE_ESTADO_DE_DESENVOLVIMENTO_ECONOMICO_CIENCA_TECNOLOGIA_E_INOVACAO = "SECRETARIA DE ESTADO DE DESENVOLVIMENTO ECONÔMICO, CIÊNCIA, TECNOLOGIA E INOVAÇÃO";
    public static final String SECRETARIA_DE_ESTADO_DE_DESENVOLVIMENTO_URBANO_E_METROPOLITANO = "SECRETARIA DE ESTADO DE DESENVOLVIMENTO URBANO E METROPOLITANO";
    public static final String SECRETARIA_DE_ESTADO_DE_EDUCACAO_E_DESPORTO = "SECRETARIA DE ESTADO DE EDUCACAO E DESPORTO";
    public static final String SECRETARIA_DE_ESTADO_DE_INFRAESTRUTURA = "SECRETARIA DE ESTADO DE INFRAESTRUTURA";
    public static final String SECRETARIA_DE_ESTADO_DE_JUSTICA_DIREITOS_HUMANOS_E_CIDADANIA = "SECRETARIA DE ESTADO DE JUSTIÇA, DIREITOS HUMANOS E CIDADANIA";
    public static final String INSTITUTO_DE_DEFESA_DO_CONSUMIDOR_PROCON_AM = "INSTITUTO DE DEFESA DO CONSUMIDOR - PROCON - AM";
    public static final String SECRETARIA_DE_ESTADO_DE_PRODUCAO_RURAL = "SECRETARIA DE ESTADO DE PRODUÇÃO RURAL";
    public static final String SECRETARIA_DE_ESTADO_DE_SAUDE = "SECRETARIA DE ESTADO DE SAÚDE";
    public static final String SECRETARIA_DE_ESTADO_DE_SEGURANCA_PUBLICA = "SECRETARIA DE ESTADO DA SEGURANCA PÚBLICA";
    public static final String CORPO_DE_BOMBEIROS_MILITAR_DO_ESTADO_DO_AMAZONAS = "CORPO DE BOMBEIROS MILITAR DO ESTADO DO AMAZONAS";
    public static final String SECRETARIA_DE_ESTADO_DO_MEIO_AMBIENTE = "SECRETARIA DE ESTADO DO MEIO AMBIENTE";
    public static final String GOVERNADORIA = "GOVERNADORIA";

}
